notifications:
  email: false

language: minimal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
  - docker build -f Dockerfile -t github.com/iot-for-tillgenglighet/integration-isycase .
  - docker tag github.com/iot-for-tillgenglighet/integration-isycase docker.pkg.github.com/iot-for-tillgenglighet/integration-isycase/integration-isycase:$TAG_PREFIX$TRAVIS_COMMIT
  - docker push docker.pkg.github.com/iot-for-tillgenglighet/integration-isycase/integration-isycase:$TAG_PREFIX$TRAVIS_COMMIT